### ISSUE TITLE
MBTA: Massachusetts Bay Transit Authority

### ISSUE THREAD

**Issue by milas** [jamespfennell/transiter#152]
(Thanks for transiter!) I hope you don't mind the rather free-from nature of this issue -- please let me know if you'd prefer something else.

With Transiter 1.0.0, I was able to load the Massachusetts Bay Transit Authority as `mbta` with this config:
```yaml
name: Massachusetts Bay Transit Authority (MBTA)

feeds:
  - id: gtfsstatic
    type: GTFS_STATIC
    url: "https://cdn.mbta.com/MBTA_GTFS.zip"

  - id: tripupdate
    type: GTFS_REALTIME
    url: "https://cdn.mbta.com/realtime/TripUpdates.pb"

  - id: alerts
    type: GTFS_REALTIME
    url: "https://cdn.mbta.com/realtime/Alerts.pb"

  - id: vehicles
    type: GTFS_REALTIME
    url: "https://cdn.mbta.com/realtime/VehiclePositions.pb"
```

### not topologically sortable
On feed update, I get this error several times:
```
error building static map: service map cannot be topologically sorted: the provided graph is not topologically sortable because it contains a cycle" system_id=mbta feed_id=gtfsstatic
```

I think it's some of the bus routes tripping it up?

Here's one that doesn't have a service map, though the route isn't actually a loop, so I'm not sure if I'm just off-base here: https://www.mbta.com/schedules/104.

Transiter API response:
<details><summary>/systems/mbta/routes/104</summary>
<p>

<pre>
{
  "id":  "104",
  "resource":  null,
  "system":  null,
  "shortName":  "104",
  "longName":  "Malden Center Station - Airport Station",
  "color":  "FFC72C",
  "textColor":  "000000",
  "description":  "Frequent Bus",
  "url":  "https://www.mbta.com/schedules/104",
  "sortOrder":  51040,
  "continuousPickup":  "NOT_ALLOWED",
  "continuousDropOff":  "NOT_ALLOWED",
  "type":  "BUS",
  "agency":  {
    "id":  "1",
    "resource":  {
      "path":  "systems/mbta/agencies/1"
    },
    "system":  {
      "id":  "mbta",
      "resource":  {
        "path":  "systems/mbta"
      }
    },
    "name":  "MBTA"
  },
  "alerts":  [],
  "estimatedHeadway":  823,
  "serviceMaps":  [
    {
      "configId":  "realtime",
      "stops":  []
    },
    {
      "configId":  "weekday",
      "stops":  []
    },
    {
      "configId":  "alltimes",
      "stops":  []
    }
  ]
}
</pre>

</p>
</details> 

### unique constraint on `transfer_system_pk_id_key`
Since the logging on the feed update didn't give me a ton of details, I figured I'd try latest `main` as a first step and possibly add some extra attributes to the slog call to figure out which route/etc are breaking.

Unfortunately, I can no longer import the system at all on HEAD:
```
level=ERROR msg="failed update with reason FAILED_UPDATE_ERROR and error \"ERROR: duplicate key value violates unique constraint \\\"transfer_system_pk_id_key\\\" (SQLSTATE 23505)\" in 3.272171761s" system_id=mbta feed_id=gtfsstatic update_id=f9841009-3632-4b66-bed7-a745b2e3ab24

level=ERROR msg="install or update failed: ERROR: duplicate key value violates unique constraint \"transfer_system_pk_id_key\" (SQLSTATE 23505)" system_id=mbta
```

### Additional Context
Again, I know this is a pretty vague issue! I will work on debugging/root causing a bit more on these, but wanted to at least share my progress publicly as a start.

With v1.0.0, things do work well in general! I'm still just getting started playing around with Transiter, but it's really awesome and something I'm SO happy exists.
