### ISSUE TITLE
Add a feature to automatically create cross-system stations based on location

### ISSUE THREAD

**Issue by jamespfennell** [jamespfennell/transiter#17]
In the GTFS static parser, Transiter uses the transfers.txt field to bundle stations like 6th Av and 14th St into one station. (This behavior is not universally desired and should be optional.)

Right now there's no way to create cross-system stations. However using the GPS data for every stop it should be able to do this in a somewhat automatic way.

Will need new endpoints to (a) search for linked stations based on geolocation and (b) add arbitrary sets of stations to one bigger stations.

**Comment by jamespfennell** [comment]
One idea is to have a system stop linking configuration. This would define conditions (system + GPS proximity) under which stops would be linked together OR have transfers created between them.

```
systems:
- us-ny-subway
- us-ny-path

strategy: GROUP_STATIONS

distance: 300

additions:

exceptions:
- - system: us-ny-subway
     stop_id: L03
  - system: us-ny-path
    stop_id: 34
```
