### ISSUE TITLE
[GTFS Full Support] Resolve stops/transfers situation 

### ISSUE THREAD

**Issue by jamespfennell** [jamespfennell/transiter#60]
We want to support:

- Having plain old transfers between arbitrary stops, sourced from `transfers.txt`. We want to expose these in the HTTP API.
- Still having a notion of grouped station, with the use case being NYC Subway stations.
- Configuring the GTFS Static parser on a feed-by-feed basis to determine the right "transfer strategy".
- Maintain the current service maps philosophy, which is that only genuine stations can be a part of a service map.

**Comment by jamespfennell** [comment]
```
feeds:

  gtfsstatic:
    http:
      url: 'http://web.mta.info/developers/data/nyct/subway/google_transit.zip'
    parser:
      built_in: GTFS_STATIC
      options:
        transfers_strategy: DEFAULT  # or GROUP_STATIONS
        transfers_exceptions: 
          - [L26, 254] 
    required_for_install: true
    auto_update:
      enabled: false
```
